### ISSUE TITLE
asset

### ISSUE THREAD

**Issue by uyekt23** [klaytn/klaytn-dex-frontend#102]
**Describe the bug**
i cant klik my asset menu

**How to reproduce**
Steps to reproduce the behavior: please fix

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [windows 11
![klay](https://user-images.githubusercontent.com/88120340/204869747-1f5bb23c-4d4c-4ba4-a936-26daceb8775a.png)
]
 - Wallet and its version metamask extension

**Additional context**
my wallet 0xdF81ec44e6a9aD53799554596e11aFd642513C92

**Comment by Homer-Klaytn** [comment]
@uyekt23 The Asset page can be accessed without any issues!

Thank you
