### ISSUE TITLE
deposit liq

### ISSUE THREAD

**Issue by uyekt23** [klaytn/klaytn-dex-frontend#103]
**Describe the bug**
canot deposit and still eror 

**How to reproduce**
Steps to reproduce the behavior: fix web again because web still slow

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the foll
![klay3](https://user-images.githubusercontent.com/88120340/204872602-f48609aa-3c4a-4b4d-ad53-481b6fb17c3c.png)
![klay2](https://user-images.githubusercontent.com/88120340/204872692-927a9a42-5e25-410e-a563-cd888ea07100.png)
please see my screenshooto)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [windows/11]
 - Wallet and its version used , metamask]

**Additional context**
please this is importan u can see my wallet 
0xdF81ec44e6a9aD53799554596e11aFd642513C92

**Comment by Homer-Klaytn** [comment]
@uyekt23 When depositing you should have no issues now
Thanks!
