### ISSUE TITLE
Feedback & Suggestions

### ISSUE THREAD

**Issue by blackid9** [klaytn/klaytn-dex-frontend#104]
hello sir, I have a suggestion for your DEX, which is to add the NFT marketplace & NFT staking, and one more thing, which is to add a price indicator beside the swap because it will really help. And I've also tried all the features on your DEX from withdraw, remove LP & unstake, I've tried everything smoothly and it works, btw I can't vote because I don't have a ticket hahaha. maybe that's all the feedback from me, sir. 🚀🚀🚀🚀

My Wallet Addres :
0x0C8c73a772D9a2d05B6fDdD6F22A9e1268B75a81

![Screenshot_2022-11-30-18-09-36-29](https://user-images.githubusercontent.com/54349488/204875492-e55ac73e-327a-4fad-b40d-d7b2c98a4732.jpg)
![Screenshot_2022-11-30-18-10-04-96](https://user-images.githubusercontent.com/54349488/204875511-cdd77aa6-6f60-4e33-8bec-b180f45d4201.jpg)
![Screenshot_2022-11-30-18-26-15-05](https://user-images.githubusercontent.com/54349488/204875518-dfbcbfd6-3e1f-4148-b167-a1dffad51847.jpg)
![Screenshot_2022-11-30-18-26-32-75](https://user-images.githubusercontent.com/54349488/204875526-76a1e39b-8ada-46ea-b3f0-d45524df4cc3.jpg)

**Comment by Homer-Klaytn** [comment]
@blackid9 Thank you for your testing and we hope to continue delivering high quality features and improvements!
