### ISSUE TITLE
Feedbac and suggestion about UI/UX

### ISSUE THREAD

**Issue by safeyz93** [klaytn/klaytn-dex-frontend#105]
There are a few key things to keep in mind when designing a UI: 

1. Keep it simple and easy to use. The last thing you want is for your users to get frustrated trying to figure out how to use your app. 

2. Make sure the design is consistent throughout. This means using similar colors, fonts, and icons throughout the app. 

3. Pay attention to the details. Small things like button size and placement can make a big difference in how easy your app is to use. 

4. Test your design with actual users. Get feedback early and often to make sure you're on the right track.

0xf98891Ec45E6A6E94A8795257Cad9f785bC6704e

**Comment by Homer-Klaytn** [comment]
@safeyz93 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
