### ISSUE TITLE
Connect wallet

### ISSUE THREAD

**Issue by 0x-lip** [klaytn/klaytn-dex-frontend#106]
![Screenshot_2022-12-01-02-34-13-33_d4b821f22c36211daa9077338f9854d0](https://user-images.githubusercontent.com/117567410/204891773-554f606b-b6ec-40e5-98bc-b6e8ba07a23a.jpg)
hello sir when I connect to my wallet for the first time it runs smoothly, but when I open a new tab my wallet is unreadable, I have to disconnect and reconnect again to make it read, please fix it, thank you 
My address: 0x0C1f8C9b144B97A87c7e872BD66420B7C671c6B2

**Comment by Homer-Klaytn** [comment]
@Subr1 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
