### ISSUE TITLE
Remove liquidity 

### ISSUE THREAD

**Issue by Hermantoo** [klaytn/klaytn-dex-frontend#107]
I want to remove kdex-weth liquidity, but in 'amount' menu it looks like this, does the site have bugs?
or am I wrong and don't know how to eliminate liquidity!

if you experience a bug, please fix it, if I'm wrong, please explain where the error is so that I will know better in the future
 Thank you
![Screenshot_2022-12-01-06-47-57-32_4d38fce200f96aeac5e860e739312e76.jpg](https://user-images.githubusercontent.com/119505342/204932848-cfd11ecb-2b60-4cbc-94b4-059fef0ed9ad.jpg)

![Screenshot_2022-12-01-06-47-50-87_4d38fce200f96aeac5e860e739312e76.jpg](https://user-images.githubusercontent.com/119505342/204932867-faa359bd-5bb0-4413-b181-0d86780ab396.jpg)

**Comment by Homer-Klaytn** [comment]
@Hermantoo We've fixed the placement issues on the page. Thank you for your testing and we hope to continue delivering high quality features and improvements!
