### ISSUE TITLE
add theme

### ISSUE THREAD

**Issue by Jarrcd** [klaytn/klaytn-dex-frontend#108]
After I tried all the features I think everything went well and found no bugs/errors, maybe in the future you can add a dark/light lighting feature to make it more comfortable during the day, thank you
my address:
0x637356AE5d6ee5Ff71951aFef611826F4eEA843B

**Comment by Homer-Klaytn** [comment]
@Jarrcd Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
