### ISSUE TITLE
Website design

### ISSUE THREAD

**Issue by Nekaryuki** [klaytn/klaytn-dex-frontend#109]
Good experience and the features that are owned are very useful and everything works, but I feel something is missing like the design on the website which is too flat, I hope this can be considered for the team to be able to provide better products to users
![Capture](https://user-images.githubusercontent.com/91670608/204947086-b746e218-20e4-4e0a-bd93-fb220a4ea7a6.JPG)

**Comment by Homer-Klaytn** [comment]
@Nekaryuki Thank you for your testing and we hope to continue delivering high quality features and improvements!
