### ISSUE TITLE
  TIM needs to fix this ASAP

### ISSUE THREAD

**Issue by Dodyharyanto** [klaytn/klaytn-dex-frontend#110]
Of all the available features, I experienced 2 errors/bugs, the first was in the swap feature and the second was in the Liquidity feature

with an experienced team I think I can fix this problem, make the most of the team as much as possible

it's normal for a new project to experience technical problems, but if it's not fixed immediately, it will boomerang on the project, the point remains to focus especially on the support team educating the community, even a big project without the community will not be successful, respect the community and input his

![eror 2](https://user-images.githubusercontent.com/68990070/204947359-b593acbb-e972-44c3-9c1b-1aafcdeb2bc6.jpeg)
![eror 1](https://user-images.githubusercontent.com/68990070/204947364-481e5382-9d5b-4715-986b-025020188c61.jpeg)

**Comment by Homer-Klaytn** [comment]
@Dodyharyanto Thank you for testing, we've fixed the liquidity and swapping issues!

Thank you for your testing and we hope to continue delivering high quality features and improvements!
