### ISSUE TITLE
token swap sometimes error

### ISSUE THREAD

**Issue by Mzikky** [klaytn/klaytn-dex-frontend#111]
when I want to swap tokens I have set slippage but when I want to swap again the slippage returns to the way it was before.. 

![Screenshot_2022-11-30-16-55-57-583_com kiwibrowser browser](https://user-images.githubusercontent.com/116237802/204948163-4955cd87-c494-417e-b5b1-00c4a81ab2e4.jpg)

**Comment by Homer-Klaytn** [comment]
@Mzikky You should have no issues swapping klay to dex!

Thanks
