### ISSUE TITLE
features

### ISSUE THREAD

**Issue by AxLiv** [klaytn/klaytn-dex-frontend#113]
**Is your request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AxLiv** [comment]
![image](https://user-images.githubusercontent.com/91681765/204952618-78aed8fe-2135-4b75-84d7-0aa2d4862275.png)

all transaction succesfull and very fast respon on wallet. Maybe add theme dark on website
my address 0x215616e265d69b106c19a0c601819a0d768b4233

**Comment by Homer-Klaytn** [comment]
@AxLiv Thank you for your testing and we hope to continue delivering high quality features and improvements!
