### ISSUE TITLE
Testnet Feedback

### ISSUE THREAD

**Issue by Hodlnft** [klaytn/klaytn-dex-frontend#115]
I have tried and completed several tasks that must be tried in the Soramitsu Testnet. I have swapped several Klay tokens in normal swaps or Multi-hops
/ Expert mode, then I added Liquidity and tried to deposit and withdraw Lp. then I go to farming / earn and stake, add, remove/withdraw Lp tokens and harvest earn tokens. everything went well and smoothly without any bugs or errors that I found in the Soramitsu Testnet. Keep growing Soramitsu and hopefully Soramitsu will be even better in the future

Address Testnet: 0xB778527eD387b19f1b31876ED286c0C0Ca9d7b16
![1](https://user-images.githubusercontent.com/115768564/204958774-98069444-7237-4559-bb1f-150900d3e688.png)

**Comment by Homer-Klaytn** [comment]
@Hodlnft Thank you for your testing and we hope to continue delivering high quality features and improvements!
