### ISSUE TITLE
bug in the delete liquidity feature

### ISSUE THREAD

**Issue by Pokahlol** [klaytn/klaytn-dex-frontend#116]
why here for balance is not there and for percentages all do not work. but to delete manually can, so here do not know how many percentages will be deleted, because it does not work. can only be manually in (DETAILED) and even then the same balance is also not displayed. 
my wallet: 0xe5b19f2fe8dcc084e34d98ec13b1b9d0d1dfeb35
![Screenshot (111)](https://user-images.githubusercontent.com/119553335/204959435-f95143dc-6ac3-479f-a974-5ff7f9139895.png)
![Screenshot (112)](https://user-images.githubusercontent.com/119553335/204959458-8b7bfe04-aa37-4364-9ce6-c517849201ec.png)

**Comment by Victorius** [comment]
Hello, @Pokahlol 
Thanks for your support in testing 1st open-source DEX on Klaytn.

Regarding you user experience in bug appearance we have several question.
Could you describe steps which you made to achieve this bug?
Try to repeat it, please.

**Comment by Homer-Klaytn** [comment]
this problem is resolved, for we werer able to confirm we can remove liquidity from using the percetnage bar from the amount page
