### ISSUE TITLE
There is a problem when trying to remove liquidity

### ISSUE THREAD

**Issue by AlGhautama09** [klaytn/klaytn-dex-frontend#117]
**Describe the bug**
From the beginning, everything went smoothly, the swap and add liquidity features but when trying to remove liquidity the transaction failed

**How to reproduce**
Steps to reproduce the behavior: Finally, I tried to re-swap the problematic token while removing liquidity and when I tried to remove it a second time it worked.

**Expected behavior**
I hope this issue is responded to quickly because to remove liquidity it is still necessary to repeat from swap to add liquidity.

[**Attachments**
<img width="870" alt="dex3" src="https://user-images.githubusercontent.com/108366042/204959252-6b4ef436-3462-4a2a-9d50-9bc019a66714.png">

**Environment (please complete the following information)**

 - OS and its version [Windows]
 - Wallet and its version used : metamask : 0xE1C1D2d9A495f97de078E82b9F37908dE53333Bd

**Additional context**
For other features it is very smooth there is no problem at all.

**Comment by Homer-Klaytn** [comment]
@AlGhautama09 Removing liquidity issues has been resolved.

Thanks
