### ISSUE TITLE
when using a mobile device at the top there is a buildup of menus making it difficult to press 

### ISSUE THREAD

**Issue by Raizel77** [klaytn/klaytn-dex-frontend#118]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [e.g. macOS/10.14]
 - Wallet and its version used [e.g. Kaikas, metamask]

**Additional context**

**Comment by Raizel77** [comment]
My addres

0xdd16B418E7F47735ca6C1119f98714e5F8b7AcA5

**Comment by Homer-Klaytn** [comment]
@Raizel77  Mobile usage of the Dex was not part of this development scope, we consider this to be a non-issue since the desktop browser is working accordingly.
