### ISSUE TITLE
Feedback request

### ISSUE THREAD

**Issue by firkawe** [klaytn/klaytn-dex-frontend#121]
The project is very good, all the features work, fast loading is very smooth. I like the color combination, very user-friendly. minimalist and subtle, but where is the dark mode? I recommend you to add dark mode because not a few people are comfortable with light mode. I am sure that when the wallet is launched, it will quickly grow rapidly.

**Comment by Homer-Klaytn** [comment]
@firkawe Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
