### ISSUE TITLE
 suggestions for website development

### ISSUE THREAD

**Issue by bakoldungo** [klaytn/klaytn-dex-frontend#122]
I don't have any serious problems. However, as a novice Dex user, I'm still a little confused when using it. maybe the dex website needs to be added with a question feature or given an example of how to use the dex.

and on adding liquidity, I think there needs to be a one-click feature to change from the first token on top and the second token on the bottom

and I think the background on the dex is still too plain, it needs to be redesigned to make it more attractive and look elegant

my address : 0x20365D5e968f570Ba800123531Be7FC08404862A

![Screenshot_20221201_124900_com kiwibrowser browser](https://user-images.githubusercontent.com/119043916/204976029-7648e179-d991-4ca2-8ac8-7bf9259f04bb.jpg)

**Comment by Homer-Klaytn** [comment]
@bakoldungo Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
