### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by babangzian** [klaytn/klaytn-dex-frontend#123]
All features work normally and there are no problems in the transaction, and the UI/UX features are good and attractive in my opinion.
but there are some things that need to be known that there are still many weaknesses in the web in terms of html is also still weak and so easily hacked or inserted scripts will also be able to be hacked. and to the team please increase the security system again thank you.

**Comment by Homer-Klaytn** [comment]
@babangzian Thank you for your testing and we hope to continue delivering high quality features and improvements!
