### ISSUE TITLE
All the feature from Klaytn Dex x Soramitsu , Testnet Address : 0x84A25c881DB2476F751B6Ece35114E96Da7dC59D

### ISSUE THREAD

**Issue by benjoz76** [klaytn/klaytn-dex-frontend#124]
All the feature from Klaytn Dex x Soramitsu 
My testnet address : 0x84A25c881DB2476F751B6Ece35114E96Da7dC59D
1. Swap Feature : This is good fast transcation also no erors or bugs I found while try the testnet 
2. Liquidity Pools : Its good no any erors we can add or remove the liquidity with non erors at the precentage 
3.Earning / Staking : Have a good transaction and quick calculating the rewards with no issues 
4. Vote feature : At the first if I wanna take vote , I always failed because the snapshot website notify in my address its none KDEX or Voting Powers its not alvailable at my wallet , So I have things to create new proposal vote on snapshot and its good , clearly my proposal have shown on vote feature at Klaytn Dex 
5. Suggestion : I things the website its good if dev wanna add the dark and light mode !! , I prefer like a dark mode than light mode, UI and UX too simple also the background of website its not attractive , Ithings its good if dev wanna give the backgrounds like anime or cartoon by klaytn logos or somethings attractive because this is WEB 3.0 with a new finance technology. 
6. Conclution :All the feature its works properly UI/UX its looks simple and easy to use , Website speed and transcation speeds its awesome its just had 1-3 sec to take the transaction approve. 
Thanks this is my review about Klaytn Dex X Soramitsu , If any wrongs with my feedbacks and suggestion I really2 sorry and gimme a forgive as a human being 👍 👍 

Screenshot of testnet : 
1.![image](https://user-images.githubusercontent.com/111244983/204992794-180c24b2-6c3c-42d6-8e8f-fa924d9bbebd.png)
2.![image](https://user-images.githubusercontent.com/111244983/204992834-c6e165a3-b7bb-41a7-a1b3-33c63798c3ea.png)
3.![image](https://user-images.githubusercontent.com/111244983/204992869-bff63bb0-9f93-4e8c-9634-bf6d9386cbe0.png)
4.![image](https://user-images.githubusercontent.com/111244983/204992909-c370f1a0-6b03-434d-96a0-217d7fcbde47.png)
5.![image](https://user-images.githubusercontent.com/111244983/204992938-aac27a83-9342-4eb5-9988-c3c552850760.png)

**Comment by Homer-Klaytn** [comment]
@benjoz76 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
