### ISSUE TITLE
FEEDBACK

### ISSUE THREAD

**Issue by penggapaicrypto22** [klaytn/klaytn-dex-frontend#125]
thank you for an extraordinary project, I am happy to be able to contribute and interact directly with the platforms of this project. I have tried all the features and operations provided. from my experience there are some recommendations for feedback and suggestions that I hope can help

Assets
1. This feature covers the entire portfolio of users by presenting the results of transaction history and ownership of the balance of assets they have
2. I think the display is too elongated downwards, maybe it can be adjusted again regarding the appearance or position, such as the example of width to the side
3. in the menu that displays the user's address it feels incomplete and detailed even though there is already a copy address button but there are some missing initial parts for 0x
4. I tried hide button but how to unhide it? add this operation

Swaps
1. This feature is very innovative because it can be adjusted according to appearance such as expert mode or enable multi hops, but as a new user this operation is quite confusing. I hope there is a direct hint available as to the differences between the two
2. the exchange process is very good regarding transactions and platform response
3. I hope there is a picture or logo of each existing asset
4. The transaction details are quite complete and good
5. Unification with liquidity in the trade feature is expected to make it easier for users, but there needs to be a display that provides which pairs are available

earn
1. available to increase income by staking lp tokens and staking kdex assets
2. The sort by feature is very helpful for knowing and filtering according to user needs
3. All operating processes go well and the display can be opened and closed for each fair, adding to the aesthetics
4. I am glad that the get lp operation which is directly directed at liquidity is quite helpful

Vote
1. the voting process is directly redirected to a snapshot but the process is too long and buffering. Turns out it requires a VPN to access it
2. very easy to customize and search which proposals are active

I hope this can be improved and this project will be successful and provide useful feedback for its users, especially the development community

0xDC48d6C5bAa082F3A0F413db79D6995950ad81A9

![photo_2022-12-01_15-17-52](https://user-images.githubusercontent.com/88971796/205001389-fba4ccd5-54bb-406e-8821-1bbdc1e2e519.jpg)
![photo_2022-12-01_15-17-54](https://user-images.githubusercontent.com/88971796/205001398-d05e1cba-8f95-4c18-af01-d3e26ad6d42e.jpg)
![photo_2022-12-01_15-17-56](https://user-images.githubusercontent.com/88971796/205001403-776e9a92-eee7-4e73-8a36-f5b9210695df.jpg)
![photo_2022-12-01_15-18-00](https://user-images.githubusercontent.com/88971796/205001405-406c3896-cdcf-433a-87a4-1f7a248ba872.jpg)
![photo_2022-12-01_15-18-02](https://user-images.githubusercontent.com/88971796/205001407-996ae9f9-3be1-477d-8976-d60ed13b7e10.jpg)

**Comment by Homer-Klaytn** [comment]
@penggapaicrypto22 Thank you for your testing and we hope to continue delivering high quality features and improvements!
