### ISSUE TITLE
Improvment in website ui

### ISSUE THREAD

**Issue by lilypoli** [klaytn/klaytn-dex-frontend#128]
**Is your request related to a problem? Please describe.**
The website looks too plain and can be enchanced by adding more graphics.
**Describe the solution you'd like**
one thing i like is the toggle switch button between light and dark mode, website can be enhanced more in the UI/UX department to make it much more eye appealing.  Also I suggest to add all social media links into the website so users dont have to find it difficult to search for them. Also to add animations in the pop up transactions would be great.

**Describe alternatives you've considered**

**Additional context**

**Comment by Homer-Klaytn** [comment]
@lilypoli Thank you for your testing and we hope to continue delivering high quality features and improvements!
