### ISSUE TITLE
UI idea

### ISSUE THREAD

**Issue by I20410** [klaytn/klaytn-dex-frontend#129]
![Screenshot_2022-12-01-16-53-16-51](https://user-images.githubusercontent.com/119587297/205029846-660d7e79-e952-48d3-a2dc-be6a80fbd8f5.jpg)

please change the UI to make it more attractive, because the current UI is less attractive (my personal opinion)

Wallet address: 0x7F044CDb08AE6b1eea42c6534E090971fb894844

**Comment by Homer-Klaytn** [comment]
@I20410 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
