### ISSUE TITLE
Bug LP 

### ISSUE THREAD

**Issue by I20410** [klaytn/klaytn-dex-frontend#130]
I can't remove LP Tokens 
please fix

OS version: Android 8
Wallet: METAMASK
Wallet address: 0x7F044CDb08AE6b1eea42c6534E090971fb894844

![Screenshot_2022-12-01-16-56-05-81](https://user-images.githubusercontent.com/119587297/205031007-a0a5250b-230e-4671-a702-595173086a80.jpg)

**Comment by Homer-Klaytn** [comment]
@I20410 You should be able to remove LP tokens. Ideally we were not developing this dex for mobile at this time. Please use a desktop browser in the future.

thank you!
