### ISSUE TITLE
ui/ux bug

### ISSUE THREAD

**Issue by naufalprtm** [klaytn/klaytn-dex-frontend#132]
**Describe the bug**
At the time of browser minimaze, the ui/ux is out of sync with size. they collide with each other

**Attachments**
![Capture](https://user-images.githubusercontent.com/103091329/205034966-f2313202-e238-42d7-baf3-eccfcbded582.PNG)

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [Windows 10]
 - Wallet and its version used [metamask]

**Comment by Homer-Klaytn** [comment]
@naufalprtm After fixing this issue, minimizing the browser casused no issues with the UI

Thanks!
