### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by larnodiki** [klaytn/klaytn-dex-frontend#133]
very smooth app...all my transactions went fast and there were no errors.I just can't vote.
![Screenshot (34)](https://user-images.githubusercontent.com/109177791/205065711-6833406a-b0b8-4636-a9f7-dbd6af240880.png)
 happy to participate in your project. LFG🔥 0xF32fBcF957dEBEE213E89B7d58b1238BfEd52776

**Comment by Homer-Klaytn** [comment]
@larnodiki Thank you for your testing and we hope to continue delivering high quality features and improvements!
