### ISSUE TITLE
I cant swap KLAYTN/DEX 

### ISSUE THREAD

**Issue by Cynwon** [klaytn/klaytn-dex-frontend#134]
**Describe the bug**
when I tried swap KLAYTN to DEX token  , I get disgusting notification 
but when I try swap KLAYTN to USDT and KLAYTN to Wemix its working I dont get disgusting notification 
maybe you can give me a reason why I cant swap that token pair.
![Screenshot_67](https://user-images.githubusercontent.com/86565562/205068856-57f54d80-c971-45b7-a759-1f5194a7072c.png)

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [e.g. macOS/10.14]
 - Wallet and its version used [e.g. Kaikas, metamask]

**Additional context**

**Comment by Homer-Klaytn** [comment]
<img width="510" alt="Screen Shot 2022-12-29 at 10 59 54 AM" src="https://user-images.githubusercontent.com/113971437/209893666-6445e326-ecb9-4665-9352-9e7b5ea89062.png">

@Cynwon You should have no issues swapping Klay to Dex!

Thanks
