### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Babiho** [klaytn/klaytn-dex-frontend#136]
I am finished this testnet. it's look good and smooth 

my address: 0x1d68fC7C741a9e7EA1FFa447eF5230d917fC244F
![dex](https://user-images.githubusercontent.com/91447378/205072819-e51fa0f6-a372-426f-9856-7d87a762f10a.png)

**Comment by Homer-Klaytn** [comment]
@Babiho Thank you for your testing and we hope to continue delivering high quality features and improvements!
