### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by tazakamila** [klaytn/klaytn-dex-frontend#137]
![Screenshot (35)](https://user-images.githubusercontent.com/112821209/205072914-2af0b527-9b2b-4116-afc9-2e9943a1d704.png)
all tasks run quickly and smoothly. can't wait for the next update. 0xB2ef2538DBd852BF004dc15f8E35dd8d9d1617d4

**Comment by Homer-Klaytn** [comment]
@tazakamila Thank you for your testing and we hope to continue delivering high quality features and improvements!
