### ISSUE TITLE
LIQUIDITY SYSTEM.

### ISSUE THREAD

**Issue by Cynwon** [klaytn/klaytn-dex-frontend#138]
**Describe the bug**
![Screenshot_69](https://user-images.githubusercontent.com/86565562/205073503-38b4f492-ff00-484c-8235-d5a73a92b6fe.png)
why when I try to add a liquidity balance in the KLAYTN / USDT token I get a notification as shown which I include below
and I don't think the liquidity system is like other DEXs that automatically detect token balances

**How to reproduce**

**Expected behavior**

maybe you can change the liquidity system and Earn system a little
making it easier and less transaction fees so that novice investors interested in investing a little money

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [e.g. macOS/10.14]
 - Wallet and its version used [e.g. Kaikas, metamask]

**Additional context**

**Comment by Homer-Klaytn** [comment]
<img width="519" alt="Screen Shot 2022-12-29 at 1 02 06 PM" src="https://user-images.githubusercontent.com/113971437/209901869-d0fa320f-827d-403a-b960-12ec03a1f46e.png">
@Cynwon You should have no problem adding KLAY/USDT Liquidity combo now!
Thanks
