### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by yourbusy** [klaytn/klaytn-dex-frontend#139]
This my Result : transaction so slow but i think no problem ,swap add LP remove everything works fine just a suggestion you can add dark light mode then add all social media and web about your project information 0x70270cFf18C35C9BC99d2C77aAFE914931810E08

**Comment by Homer-Klaytn** [comment]
@yourbusy Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
