### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by suneoyadi** [klaytn/klaytn-dex-frontend#140]
![Screenshot (36)](https://user-images.githubusercontent.com/112821405/205084262-5b7c8cdf-e509-4a25-a9f3-15faa1bd3547.png)
![Screenshot (37)](https://user-images.githubusercontent.com/112821405/205084283-b579d0f6-5178-469b-816e-cc8ce07bdc4e.png)
![Screenshot (38)](https://user-images.githubusercontent.com/112821405/205084300-921fec45-89a5-4c86-aa50-dbbb1873dbbe.png)
the app is running fine. My transaction went quite fast according to my expectations. web animation, UI, UX is very comfortable to look at...can't wait to see the next development!!!😃 0x49e3560B295A61B4d1C2a86d1EA2aA2bf5d73613

**Comment by Homer-Klaytn** [comment]
@suneoyadi Thank you for your testing and we hope to continue delivering high quality features and improvements!
