### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by rinagefa** [klaytn/klaytn-dex-frontend#141]
![Screenshot (39)](https://user-images.githubusercontent.com/112821593/205090217-800c1f40-1627-4760-bda0-0a738d137a1b.png)
![Screenshot (40)](https://user-images.githubusercontent.com/112821593/205090240-fd789db4-07e6-429c-8194-bf3965ddfb5a.png)
![Screenshot (41)](https://user-images.githubusercontent.com/112821593/205090264-0c86235c-953c-48ce-8335-e5283e4db982.png)

everything works normally ... no problems that I encountered. very proud to be the initial community that supports your project...I hope it will be better in the future. 0x72a901836e0cE2812Af063B1DeC0A2317e9Aa4A9

**Comment by Homer-Klaytn** [comment]
@rinagefa Thank you for your testing and we hope to continue delivering high quality features and improvements!
