### ISSUE TITLE
Sugestion and feedback

### ISSUE THREAD

**Issue by veranisty** [klaytn/klaytn-dex-frontend#142]
Tried all existing features and everything runs normally.
UX/UI web is user friendly, however there are a few things that should be improved or added in my opinion..
**For example 1** "_in the footer section add social media icons" so that users can easily connect directly to the community_.
**Example 2** "_web page background is blank and boring, if you add a dark color option it will be more attractive, that's all in my opinion, the rest is all good_.

**My address: 0x5555C5c38E777A0ACAa8BEAeE384C066af62734a**

**Comment by Homer-Klaytn** [comment]
@VeraKaya Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
