### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Willi1210** [klaytn/klaytn-dex-frontend#143]
here maybe I don't find a problem, an error transaction or get a bug
but after i tried all features from start :
1. swap
2. add and remove liquidity
3. farming stake, unstake LP and withdraw
4. pools stake, unstake kdex and withdraw
all, there was no error in the transaction that I made

for features I think it's complete
for the background color on the background screen I think there should be a little more color
example like in other dex, take the theme from the color of your own project
for the UI / UX system it is good and normal

the development of this project in the future try to add the bridge feature, because there are not many other projects that use the bridge feature from the Clay network to other networks

my address : 0x22811ae1fD7fadB11b6D430368111A451983C100

Thank you sir. I hope your project will progress and develop in the present and in the future, here we as a community will support this project

![2022-12-01](https://user-images.githubusercontent.com/74752411/205109600-54ad16ac-ae99-4dda-83ef-8bd4eb47565c.png)

**Comment by Homer-Klaytn** [comment]
@Willi1210 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
