### ISSUE TITLE
Suggestion 1

### ISSUE THREAD

**Issue by CesarK2604** [klaytn/klaytn-dex-frontend#144]
No ui switch mode feature (Bright or Night Mode)

**Describe the solution you'd like**
The ui switch mode feature (Bright or Night Mode) needs to be added to visually increase user comfort

**Describe alternatives you've considered**
Can change the choice of colors that can make the user's eyes comfortable when used in a dark or bright room

**Comment by Homer-Klaytn** [comment]
@CesarK2604 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
