### ISSUE TITLE
Suggestion 2

### ISSUE THREAD

**Issue by CesarK2604** [klaytn/klaytn-dex-frontend#145]
**Is your request related to a problem? Please describe.**
Less practical in inputting the available balance quickly

**Describe the solution you'd like**
Need to add a percentage-based input balance option, especially on the swap feature

**Describe alternatives you've considered**
you also need to add an input balance based on prices at the dollar exchange rate, this can be a differentiator from other apps

My Wallet : 0x8B011EB29eC73aF3FF72F492ca2E778723969a2A

**Comment by Homer-Klaytn** [comment]
@CesarK2604 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
