### ISSUE TITLE
Feedback Testnet

### ISSUE THREAD

**Issue by mrstuti** [klaytn/klaytn-dex-frontend#146]
I hope there will be an increase in the features of the asset section, it doesn't look good, it should be changed to make it more attractive, such as adding daily PNL / profit and please also add transaction history so that users can more easily check each transaction it would be nice not to mix earnings and liquidity so that people can know which is the liquidity pool and which is the earn pool for farming and staking 

0x53f792e5442E7454BFc2c01Ac8A62976B4d35EbD

**Comment by Homer-Klaytn** [comment]
@mrstuti Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
