### ISSUE TITLE
when I add liquidity from Klay to Dai there is a problem "error preparation failed" I don't know if it's a bug or what

### ISSUE THREAD

**Issue by angga1222** [klaytn/klaytn-dex-frontend#147]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [e.g. macOS/10.14]
 - Wallet and its version used [e.g. Kaikas, metamask]

**Additional context**

**Comment by Homer-Klaytn** [comment]
@angga1222 Added liquidity Klay to Dai with no issues 
Thanks!
