### ISSUE TITLE
Everything is so perfect. Hopefully the project will run smoothly and always be successful

### ISSUE THREAD

**Issue by untukibu** [klaytn/klaytn-dex-frontend#149]
**Is your request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Homer-Klaytn** [comment]
@untukibu Thank you for your testing and we hope to continue delivering high quality features and improvements!
