### ISSUE TITLE
Feedback Testnet 

### ISSUE THREAD

**Issue by untukibu** [klaytn/klaytn-dex-frontend#150]
![Screenshot_20221202-020445](https://user-images.githubusercontent.com/117562811/205141124-5d017ff9-f380-4ef4-9755-19be57cad6b9.jpg)

I didn't find any bugs. That's a sign that the web is perfect but I hope to always improve the system so that it is perfect. And I hope the project runs smoothly and successfully 🎉
0x1044d569C33F89CADADE39442216e7CFef2d4D14

**Comment by Homer-Klaytn** [comment]
@untukibu Thank you for your testing and we hope to continue delivering high quality features and improvements!
