### ISSUE TITLE
I have tried all the features to see from the details of the animation and the smooth movement of your app, and everything is going well, there is not a single obstacle that in my opinion is fatal, in my opinion all of your features are amazing, I respect your team and I hope to be able to follow  all the projects you make for all communities, keep up the enthusiasm, I keep trying your website continuously and if I get a problem I will make a report to your team I hope your team can handle and respond to all the complaints, thank you

### ISSUE THREAD

**Issue by kakajack12** [klaytn/klaytn-dex-frontend#151]
I have tried all the features to see from the details of the animation and the smooth movement of your app, and everything is going well, there is not a single obstacle that in my opinion is fatal, in my opinion all of your features are amazing, I respect your team and I hope to be able to follow  all the projects you make for all communities, keep up the enthusiasm, I keep trying your website continuously and if I get a problem I will make a report to your team I hope your team can handle and respond to all the complaints, thank you🔥

0x573059CCcBdac1F3Dc65500a438C147b631807DD

**Comment by Homer-Klaytn** [comment]
@kakajack12 Thank you for your testing and we hope to continue delivering high quality features and improvements!
