### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by galangbaelah** [klaytn/klaytn-dex-frontend#152]
This project is really great, the features are interesting and there are some things that make me really like it, namely: 1. the transaction is fast 2. Elegant and easy to use 3. the user can understand the menu perfectly 4. There are no defects in the design 5. the product runs according to what the user expects always success and hopefully it can be a promising project when mainnet arrives.

0xdD152520DcEBDe2Fd2a8cb0457662f4Fae6562BA

**Comment by Homer-Klaytn** [comment]
@galangwirano23 Thank you for your testing and we hope to continue delivering high quality features and improvements!
