### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jokopurwa** [klaytn/klaytn-dex-frontend#153]
Feedback

I'm so happy to have tried and used your app/dapps what a great experience to be one of the people to try this! we hope what happens here will be a success on mainnet and all the hard working team i really appreciate your efforts.

0x7518B18042308070717ecD6A6402850a06D1C029

**Comment by Homer-Klaytn** [comment]
@jokopurwa Thank you for your testing and we hope to continue delivering high quality features and improvements!
