### ISSUE TITLE
Add percent button on unstake

### ISSUE THREAD

**Issue by ghost** [klaytn/klaytn-dex-frontend#154]
When unstaking, the amount of LP Tokens must be inputted manually or using the max button. I think this is less practical if the user wants to unstake some LP Tokens. Add a percent button like in remove liquidity to make it easier for users.

wallet address: 0xa36aca10170185f663c804f36e69d6ba0c62ced5

**Comment by Homer-Klaytn** [comment]
@endahendol Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
