### ISSUE TITLE
Failed to derived token

### ISSUE THREAD

**Issue by Palti23** [klaytn/klaytn-dex-frontend#157]
Error when i want to farm.
With description: error missing revert data in call exception.
![Screenshot_20221202-115420_Kiwi Browser](https://user-images.githubusercontent.com/94911934/205218110-d2a614f1-ccda-43d1-834b-f7efcff60ad5.jpg).

Address: 
0xad468208c96c2b4475a6439b0923f0c3c245de41

**Comment by Homer-Klaytn** [comment]
@Palti23 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
