### ISSUE TITLE
Failed to swap Klay - USD.

### ISSUE THREAD

**Issue by Palti23** [klaytn/klaytn-dex-frontend#158]
I increased the slippage tolerance to 5% but still failed.
Address: 
0xad468208c96c2b4475a6439b0923f0c3c245de41
![Screenshot_20221202-114633_Kiwi Browser](https://user-images.githubusercontent.com/94911934/205218754-87e587f9-5b5e-46ce-9eb4-075e1eb93ccf.jpg)

**Comment by Homer-Klaytn** [comment]
<img width="551" alt="Screen Shot 2022-12-29 at 11 03 24 AM" src="https://user-images.githubusercontent.com/113971437/209893878-60277c4b-a87f-4ffd-ba9f-270ffddb0360.png">
@Palti23 I was even able to run the swap at 0.1% now after the fix! 

thanks
