### ISSUE TITLE
Its very good,no issue..My wallet 0x877924a6fe37920ab0a4aa5cfb46888482805e36

### ISSUE THREAD

**Issue by cahya23** [klaytn/klaytn-dex-frontend#159]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [e.g. macOS/10.14]
 - Wallet and its version used [e.g. Kaikas, metamask]

**Additional context**

**Comment by Homer-Klaytn** [comment]
Thank you for your support @cahya23 
We will work harder to provide a better user experience
