### ISSUE TITLE
Content Security Policy (CSP) Header Not Set

### ISSUE THREAD

**Issue by toni1395** [klaytn/klaytn-dex-frontend#160]
**Describe the bug**
Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks. These attacks are used for everything from data theft to site defacement or distribution of malware. CSP provides a set of standard HTTP headers that allow website owners to declare approved sources of content that browsers should be allowed to load on that page — covered types are JavaScript, CSS, HTML frames, fonts, images and embeddable objects such as Java applets, ActiveX, audio and video files.

**How to reproduce**
Ensure that your web server, application server, load balancer, etc. is configured to set the Content-Security-Policy header, to achieve optimal browser support: "Content-Security-Policy" for Chrome 25+, Firefox 23+ and Safari 7+, "X-Content-Security-Policy" for Firefox 4.0+ and Internet Explorer 10+, and "X-WebKit-CSP" for Chrome 14+ and Safari 6+.
![csp ](https://user-images.githubusercontent.com/68943099/205257434-4c9a4c37-8d05-4069-b0a1-e38a1fb79710.png)

**Expected behavior**
![csp ](https://user-images.githubusercontent.com/68943099/205257528-eaa97600-efe4-4f71-abd3-31d943fd229e.png)

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [e.g. macOS/10.14] windows 10
 - Wallet and its version used [e.g. Kaikas, metamask] Metamask

**Additional context**
impact : 
- Changing non-sensitive details of other users (including modifying browser local storage) without already-connected wallet interaction and with up to one click of user interaction, such as changing the first/last name of user, or en/disabling notification
- Injecting/modifying the static content on the target application without Javascript (Reflected) such as reflected HTML injection or loading external site data
- Redirecting users to malicious websites (Open Redirect)

**Comment by Homer-Klaytn** [comment]
@toni1395 Thank you for your testing and we hope to continue delivering high quality features and improvements!
