### ISSUE TITLE
Some errors 

### ISSUE THREAD

**Issue by fairchildftw** [klaytn/klaytn-dex-frontend#165]
**Describe the bug**
Faced some errors in the dex.

During staking lp: https://imgur.com/a/C82HJfx
During swapping: https://imgur.com/a/PegTOxh
https://imgur.com/a/ctXiC8T

**Comment by Homer-Klaytn** [comment]
@fairchildftw After the fix, was able to stake the Weth-Link combination, Klay and Dex swap works moothly as well

Thank you
