### ISSUE TITLE
Failed Supply - Add liquidity

### ISSUE THREAD

**Issue by Cryptobusy8** [klaytn/klaytn-dex-frontend#168]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - Add liquidity - Supply - Preparation Failed
 - Android and its version 12
 - Yandex Alpha browser (Metamask extention)

**Additional context**
![Screenshot_20221206-222258_Browser Alpha](https://user-images.githubusercontent.com/100507227/205953069-43f9c23f-1557-42ba-a670-674a4bd368bb.jpg)

**Comment by Homer-Klaytn** [comment]
@Cryptobusy8 adding Liquidity issues have been resolved.

thanks
