### ISSUE TITLE
feedback and enhancements

### ISSUE THREAD

**Issue by toprakdere** [klaytn/klaytn-dex-frontend#169]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [e.g. macOS/10.14]
 - Wallet and its thank you for this amazing testnet
i have done all features, all features run smoothly and comfortable to use 
i am sure people will get a comfortable experience I will support this project 
bugs
*sometimes Failed to swap Klay - USD also i have incresed slippage %5
*sometimes  add liquidity from Klay to Dai there is a problem "error preparation failed"
*sometimes   can't vote even though there is a balance 
*UI/UX isn't responsive,balance is not synchronized, actually I have 500 KLAY test, that's increase from the faucet.
 But on asset menu it's only at least 300 KLAY test.
* in mobile mod the placement of elements that are not in place and fonts are not good

enhancements
*add theme and dark/light mode
*add an input balance based on prices $ exchange rate
*add transaction history
0x0084097e1ddee3aea0c6fbc8d381577ab6a5f0b0 used [e.g. Kaikas, metamask]

**Additional context**

**Comment by Homer-Klaytn** [comment]
@toprakdere 
Bugs
*sometimes Failed to swap Klay - USD also i have incresed slippage 5%:  **Klay Swapping issues have been resolved**

*sometimes add liquidity from Klay to Dai there is a problem "error preparation failed":  **Adding liquidity issues have been resolved as well**
*sometimes can't vote even though there is a balance: **Voting you would need Dex coins or earned Dex from farming**
*UI/UX isn't responsive,balance is not synchronized, actually I have 500 KLAY test, that's increase from the faucet.
But on asset menu it's only at least 300 KLAY test.: **The UI/UX is much more responsive now, and if it doesnt update your balance immediately after your faucet, a refresh button would update the old to new balance**
In mobile mod the placement of elements that are not in place and fonts are not good**: **The mobile placements of icons and fonts were not in the scope of this release but they are adjusted and fixed**
