### ISSUE TITLE
feedback and enhancements

### ISSUE THREAD

**Issue by toprakdere** [klaytn/klaytn-dex-frontend#170]
**Is your request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

thank you for this amazing testnet
i have done all features, all features run smoothly and comfortable to use 
i am sure people will get a comfortable experience I will support this project 
bugs
*sometimes Failed to swap Klay - USD also i have incresed slippage %5
*sometimes  add liquidity from Klay to Dai there is a problem "error preparation failed"
*sometimes   can't vote even though there is a balance 
*UI/UX isn't responsive,balance is not synchronized, actually I have 500 KLAY test, that's increase from the faucet.
 But on asset menu it's only at least 300 KLAY test.
* in mobile mod the placement of elements that are not in place and fonts are not good

enhancements
*add theme and dark/light mode
*add an input balance based on prices $ exchange rate
*add transaction history
0x0084097e1ddee3aea0c6fbc8d381577ab6a5f0b0

**Comment by Homer-Klaytn** [comment]
@toprakdere Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
