### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by mastan29** [klaytn/klaytn-dex-frontend#175]
![image](https://user-images.githubusercontent.com/118398195/206885821-d13edcaf-9563-4755-9f41-8155d589da89.png)The UI display is simple but lacking in color
Suggestions when mainnet is to add additional colors and patterns to the basic appearance so that it is more comfortable for the user's eyes

**Comment by Homer-Klaytn** [comment]
@mastan29 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
