### ISSUE TITLE
I think it's good, easy to understand and the display doesn't confuse people

### ISSUE THREAD

**Issue by HafidhIvansyah** [klaytn/klaytn-dex-frontend#176]
**Is your request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Homer-Klaytn** [comment]
@HafidhIvansyah Thank you for your testing and we hope to continue delivering high quality features and improvements!
