### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by HadiiID** [klaytn/klaytn-dex-frontend#179]
please add theme dark mode and design theme, btw in like UI UX 
my address 0x653342cbd8d40f412cf80296836cb828c33ef35b
![Screenshot (39)](https://user-images.githubusercontent.com/107876027/209255719-a1f47aed-c3d7-4796-b3c2-5716a8275ac7.png)

**Comment by Homer-Klaytn** [comment]
@HadiiID Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
