### ISSUE TITLE
no problems that i found

### ISSUE THREAD

**Issue by MargoNY95** [klaytn/klaytn-dex-frontend#181]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [e.g. macOS/10.14]
 - Wallet and its version used [e.g. Kaikas, metamask]

**Additional context**

**Comment by Homer-Klaytn** [comment]
@MargoNY95 Thank you for your testing and we hope to continue delivering high quality features and improvements!
