### ISSUE TITLE
Mobile wallet

### ISSUE THREAD

**Issue by Silent-netuzen** [klaytn/klaytn-dex-frontend#22]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [e.g. macOS/10.14]
 - Wallet and its version used [e.g. Kaikas, metamask]

**Additional context**
Cant use to mobile wallet cant conected to dex

**Comment by Victorius** [comment]
Thanks @Indahjelita for your feedback. 
For this bug I would say that right now DEX doesn't support mobile wallets. We will consider it as feature for improvement.

**Comment by Homer-Klaytn** [comment]
The label has changed from bug to enhancement
