### ISSUE TITLE
cross chain

### ISSUE THREAD

**Issue by Koloneludin** [klaytn/klaytn-dex-frontend#23]
**Is your request related to a problem? Please describe.**
A clear and concise description of what the problem is.
almost no problem everything working good and normal
**Describe the solution you'd like**
i think if there is available bridge feature that will be a good idea**Describe alternatives you've considered**

**Additional context**

**Comment by Victorius** [comment]
Thanks, @Koloneludin , for feedback!
We will consider how to implement your proposal and add cross chain support to DEX. If you have any ideas how to achieve it, feel free to share it.

**Comment by Homer-Klaytn** [comment]
@Koloneludin 
Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
