### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by elnen** [klaytn/klaytn-dex-frontend#24]
**Describe the bug**
1. wallet sometimes likes to say not enable even though it's already connected
2. Liquidity farms sometimes fail on the first try

**How to reproduce **
1. Improved the transaction again

**Expected behavior **
1. Connecting the wallet is easy and doesn't fail
2. Farm liquidity transactions took place successfully

**Attachments**
![Screenshot_2022-11-30-12-20-22-267_com yandex browser](https://user-images.githubusercontent.com/80688728/204714042-074353bc-ea0e-4e46-86b5-24ddbe47e5fb.jpg)
![Screenshot_2022-11-30-12-20-13-577_com yandex browser](https://user-images.githubusercontent.com/80688728/204714049-c353c776-2734-4b75-b39b-e3e9b7b8b483.jpg)

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue : https://dex.baobab.klaytn.net/swap
 - OS and its version [e.g. macOS/10.14] : Chrome
 - Wallet and its version used [e.g. Kaikas, metamask] : Metamask versi new

**Additional context**

**Comment by Victorius** [comment]
Hello, @elnen!
Thanks for your report. We will review it and try to fix.

**Comment by Homer-Klaytn** [comment]
connected and disconnected wallet many times without any issues 
Farm liquidity transactions had no issues and were quick
