### ISSUE TITLE
Review and feedback

### ISSUE THREAD

**Issue by kulicrypto** [klaytn/klaytn-dex-frontend#25]
hi, im testnet user you DEX almost perfect but there're some issue that i confused.

review: all is good on swap, earn and stake
issue: cannot remove LP
thanks

my wallet
0x7afc7a6CF727308CB211E2396088041F33C60e11

**Comment by Homer-Klaytn** [comment]
@kulicrypto 
We have fixed the issues in regarding to removing the removing staked Liquidity. Thank you for your testing and we hope to continue delivering high quality features and improvements!
