### ISSUE TITLE
Good project

### ISSUE THREAD

**Issue by Algianm12** [klaytn/klaytn-dex-frontend#26]
![Screenshot 2022-11-30 175815](https://user-images.githubusercontent.com/111406655/204778951-f844082a-da9e-4f54-8f55-fcf88b7d71ab.png)

A good project and strong team in a predictable and transparent road map , planned and projected. I think in the near future we will see an unprecedented growth of this project.

**Comment by Homer-Klaytn** [comment]
@Algianm12 
Thank you for testing our Dex testnet, we hope to continue delivering high quality items for this project!
