### ISSUE TITLE
I've tried all the features currently available.

### ISSUE THREAD

**Issue by zainal99** [klaytn/klaytn-dex-frontend#27]
I've tried all the features currently available.
I like the simplicity of this app. It's very easy to understand as well as operate.
I tried to swap, add liquidity and remove liquidity no problem at all. The transaction process is relatively fast. I didn't find any problems in opening and closing positions. However, I think there is still a need to add more features to make it easier for users to analyze price movements and determine positions. I hope more features will be unlocked soon and I'll be happy to try again 

my address : 0x8aE5d75Df2800AEAd7fB04Ab6E98D19D83dd03a6

**Comment by Homer-Klaytn** [comment]
@zainal99 
Thank you for your suggestions and testing our Dex!
