### ISSUE TITLE
Bug in the remove liquidity

### ISSUE THREAD

**Issue by kinkayrik** [klaytn/klaytn-dex-frontend#29]
I added liquid about four token pairs. but when I remove liquid, one pair of tokens, almost three pairs of tokens, which I add liquidity, also remove all liquid. And the only one left that I added liquidly
![Screenshot_2022-11-30-18-01-04-066_com kiwibrowser browser](https://user-images.githubusercontent.com/100072099/204779989-b0153443-cce9-4983-a2a7-07c844145a87.jpg)

Address: 0x24aea31Dd03Dda163e18c376774fFd468754d239

**Comment by Homer-Klaytn** [comment]
This issue has been tested on BaoBab

Added multiple liquidity combinations, after staking multiple combination of coins, unstaked a small portion of LP tokens. When i had multiple pair coins in my liquidity and removed a certain combination liquidity, (Whole and small percentage) it worked perfectly fine and the other liquidated coins were not affected
