### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Wedspierre** [klaytn/klaytn-dex-frontend#31]
UI/UX runs smoothly , also fast transaction. there are no problems or errors, everything works as it should. maybe there are some suggestions , please add dark mode because not everyone is comfortable with light mode.

My address 0x0000001089167600c25258Da29d2e2c857ec1689

**Comment by Homer-Klaytn** [comment]
@Wedspierre Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
