### ISSUE TITLE
Nothing wrong. Good Job. Just want to suggest 2 things.

### ISSUE THREAD

**Issue by wggear** [klaytn/klaytn-dex-frontend#32]
Feedback:
- I like the UI. So simple. Easy to understand.
- Swapping, LP was easy.
- Good job for the ROI Calculator. It made life easier.
- I apprectiate the assets and transactions list. It's a simple feature but not every projects had it.
- The font and background color was okay.
- The website was fast to load.
- Claiming from Farms and Pools worked fine.

Suggestion:
- Add a dark mode. Option always good.
- Make the font bigger for "assets, trade, earn, voting, charts"

Overall, a very solid web with a good amount of feature for Klaytn ecosystem.
![image](https://user-images.githubusercontent.com/86527575/204781178-24e31e58-6a9e-40e7-93a9-be0e899fa2e5.png)

**Comment by Homer-Klaytn** [comment]
@wggear Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
