### ISSUE TITLE
 feedback And advice

### ISSUE THREAD

**Issue by jackicen** [klaytn/klaytn-dex-frontend#33]
My address :0x61cDCc0DC52d262aBF59C3E2d1990942d982BeF3

Feedback
1. The swap feature works fine
2. The LP feature runs fine with no problems
3. Smooth earn feature
The web runs fine, there are no problems when I do the testing 

Suggestions for the future 
1. The chart menu has been repaired again because it takes a long time to open it
2.Increase web speed again, change the appearance of the web to be more beautiful, add other features such as the presentation feature 25% 50% 75% in the swap menu when you want to fill in the number of tokens

**Comment by jackicen** [comment]
Good

**Comment by Homer-Klaytn** [comment]
@Munawir090102 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
