### ISSUE TITLE
Icon placement

### ISSUE THREAD

**Issue by saktir080** [klaytn/klaytn-dex-frontend#35]
From the user interface, I think it is very easy to understand and the use of colours is also interesting, all transactions also run quickly and smoothly. But, there are somethings that are disturbing such as the placement of elements that are not in place and the use of very bad fonts while in mobile mode, therefore it seems that it would be more interesting if it was improved by using fonts that fit the theme and the use of elements that fit the place. While in desktop mode everything works fine

Klay testnet address : 
0x4aA06cDE891Bf049F2C59927400E48098645B7dF

![Screenshot_2022-11-30-18-03-25-99_d4b821f22c36211daa9077338f9854d0](https://user-images.githubusercontent.com/82067555/204781239-c9ece5ea-df92-484c-a847-1e9146d4a831.jpg)

![Screenshot_2022-11-30-18-04-32-77_d4b821f22c36211daa9077338f9854d0](https://user-images.githubusercontent.com/82067555/204781268-21d99c8b-a333-4758-b05e-30605835fa07.jpg)

**Comment by Homer-Klaytn** [comment]
@saktir080 Mobile usage of the Dex was not part of this development scope, we consider this to be a non-issue since the desktop browser is working accordingly.
