### ISSUE TITLE
Feedback and advice

### ISSUE THREAD

**Issue by saktir080** [klaytn/klaytn-dex-frontend#36]
From the user interface, I think it is very easy to understand and the use of colours is also interesting, all transactions also run quickly and smoothly. But, there are somethings that are disturbing such as the placement of elements that are not in place and the use of very bad fonts while in mobile mode, therefore it seems that it would be more interesting if it was improved by using fonts that fit the theme and the use of elements that fit the place. While in desktop mode everything works fine

Klay testnet address : 
0x4aA06cDE891Bf049F2C59927400E48098645B7dF

![Screenshot_2022-11-30-18-03-25-99_d4b821f22c36211daa9077338f9854d0](https://user-images.githubusercontent.com/82067555/204782569-e8dc5ac4-43c8-4291-9c26-e730d692d119.jpg)

![Screenshot_2022-11-30-18-04-32-77_d4b821f22c36211daa9077338f9854d0](https://user-images.githubusercontent.com/82067555/204782624-f3ab1548-445d-4328-b504-3e62a06c05fc.jpg)

**Comment by Homer-Klaytn** [comment]
@saktir080 Thank you for testing, and the placements for the Dex within the mobile browser was an issue that we were aware of but the mobile browser UI implementation was not part of this scope. We will make future enchancements about the browser placements on the mobile browser UI.

Thank you
