### ISSUE TITLE
The UI/UX isn't responsive

### ISSUE THREAD

**Issue by PanjiHikaru27** [klaytn/klaytn-dex-frontend#37]
![IMG_20221130_181541_892](https://user-images.githubusercontent.com/53354481/204782727-17a1b571-cb6c-4f46-993c-046966a99623.jpg)
The UI/UX isn't responsive, I suggest you to improve the UI/UX in term of the smooth transaction. My balance is not synchronous, actually I have at least 256 KLAY test, that's increase from the faucet. But on asset menu it's only at least 109 KLAY test. 

My Address: 0x6B1c9112Df0bE9D9A3e8987A96584519f6f81946

**Comment by Homer-Klaytn** [comment]
@PanjiHikaru27 After fixing and testing the UI/UX is much more responsive and your balance should update after one asset/transaction reset! 
Thanks
