### ISSUE TITLE
Remove LP issue

### ISSUE THREAD

**Issue by sunflover15** [klaytn/klaytn-dex-frontend#43]
All features have been working properly, although the transactions were quite slow. 
I can claim faucet, trading, adding LP,  farming, etc without any problem
The only problem that I faced is when trying to remove LP
( The " remove LP" button didn't give any response although I've clicked it several times, and after refreshing the page & reconnecting my wallet about 3-4x, finally I got succesfull to remove my LP)
 So please fix this issue. 
My address: 0xd942875817988CeE8687fcA8428C7a14DC2B6041

**Comment by Homer-Klaytn** [comment]
@sunflover15  Thank you for your testing we have fixed that issue in regards the removing the LP. 

We hope to continue delivering high quality features and improvements!
