### ISSUE TITLE
An error while trying swap klay to other coin and add liq

### ISSUE THREAD

**Issue by StephanieAgatha** [klaytn/klaytn-dex-frontend#44]
Hii.please fix a bug where too much error lfor swap and add liq.

this is example error
https://baobab.scope.klaytn.com/tx/0x77b0c087c954edd1c86a82044d52906f16f7840f1a00b2ff28956ef8b2216820

**Comment by Homer-Klaytn** [comment]
@StephanieAgatha We've fixed this issue with swapping and adding liquidity. We thank you for testing and hope to continuously improve our dex in the near future!
