### ISSUE TITLE
Remove LP Failed

### ISSUE THREAD

**Issue by 0xhnf** [klaytn/klaytn-dex-frontend#45]
always fails when deleting LP.
my address
0xE8E5909dAe931d39c0d068D5896DB656ff87D1db
![Screenshot_20221130_191323](https://user-images.githubusercontent.com/100915517/204783379-bdd62865-4286-44e2-ae40-b01235bdad83.jpg)

**Comment by Homer-Klaytn** [comment]
@mandaybatanax  Does not fail anymore based on multiple tests
