### ISSUE TITLE
Please add 'Claim All' on Earn

### ISSUE THREAD

**Issue by kevinyusuf1607sw** [klaytn/klaytn-dex-frontend#46]
Hi team, i have a suggestion about feature request. Right now if user want to claim rewards, user need to claim it one by one. How about add Claim all features so user will be easier to claim all rewards they get from farming LP and staking KDEX? it will be a plus point for Klaytn DEX.

Also on wallet address section it will be good if provided with link to klaytn explorer. Lastly, i think it will be good if Charts is available on Trade rather than on different section.

I think it's only suggestion i can give for Klaytn DEX. Hopefully this can help, thanks

**Comment by Homer-Klaytn** [comment]
@kevinyusuf1607sw Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
