### ISSUE TITLE
suggest & idea

### ISSUE THREAD

**Issue by ezaryosepiyan** [klaytn/klaytn-dex-frontend#47]
![Screenshot_2022-11-30-18-16-42-95](https://user-images.githubusercontent.com/43679550/204782584-f8c69558-3168-4405-9dab-8eadfffea530.png)
I think it's pretty good, simple, I like it, but on the price dex feature, it's good to fix, in my opinion it's not neat.

my address: 0xf4424c46f42fda089c99951311c56acd06b71a41

**Comment by Homer-Klaytn** [comment]
@ezaryosepiyan Thank you for your testing and we hope to continue delivering high quality features and improvements!
