### ISSUE TITLE
Wallet not enable

### ISSUE THREAD

**Issue by ghost** [klaytn/klaytn-dex-frontend#48]
I found a problem when I entered the chart menu and returned to the dex swap page, it said wallet not enable and it often happens, the other features are very good,

Wallet used : 0x1503259c505A39497487FaE967B4cfC8E0aBa031

**Comment by Homer-Klaytn** [comment]
@aorakun We fixed the issue and shouldnt have any issues with the wallet not being enabled after you enter the chart menue
