### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Inki1** [klaytn/klaytn-dex-frontend#49]
After I tried all the available features, everything went well, nice display. i love the ui/ux. it's simple and easy to use for new user,
all features is working, speed loading very smooth, i tried on many device resolution and it's working perfectly 
 my address wallet
0x44cb9Ff76a361df0DC3ad25C3ed9335Dab1b6758

**Comment by Homer-Klaytn** [comment]
@Inki1 Thank you for your testing and we hope to continue delivering high quality features and improvements!
