### ISSUE TITLE
Bug on Remove Liquidity and Wallet Address

### ISSUE THREAD

**Issue by kevinyusuf1607sw** [klaytn/klaytn-dex-frontend#50]
Hi team i want to report 2 bugs i found on Klaytn DEX :
1. Remove Liquidity not working
![image](https://user-images.githubusercontent.com/100916432/204784166-d7d1bb53-31ce-40e3-a90c-4f80a01b95e6.png)

![image](https://user-images.githubusercontent.com/100916432/204784271-fbeb0c35-d482-4fc0-bf58-252214cb4a16.png)

![image](https://user-images.githubusercontent.com/100916432/204784289-6eb160a5-5d62-4727-871e-1d71ff1bb100.png)

As you can see i have DAI-WKLAY LP, but when i want to remove my liquidity, it's not working. Only blank. Please fix it team

2. Wallet Address 0x is not shown
![image](https://user-images.githubusercontent.com/100916432/204784610-71e7c975-c9f7-48f0-ba3e-533300dea28a.png)

As you can see there is no 0x on wallet address on red circle, please fix it team.

I will be glad if it's fixed before mainnet, thanks

**Comment by Homer-Klaytn** [comment]
The Liquidity issue has been fixed, but the 0x on the wallet address has not been, but will it need to be?

**Comment by Homer-Klaytn** [comment]
@kevinyusuf1607sw the 0x has been added on the wallet address

**Comment by kevinyusuf1607sw** [comment]
thanks for fixing it team
