### ISSUE TITLE
can't swap

### ISSUE THREAD

**Issue by dwirizaldy20** [klaytn/klaytn-dex-frontend#51]
**Describe the bug**
Failed to swap with pair klytn/dex

**How to reproduce**
Trade or swap pair klytn->dex

**Expected behavior**
create/replace new smartcontract address

**Attachments**
![swap1](https://user-images.githubusercontent.com/87029845/204782937-3521b051-f582-4483-9138-50cdad5076b9.jpg)
![swap2](https://user-images.githubusercontent.com/87029845/204782984-355c30c9-bea2-4669-958d-43595b508813.jpg)

**Environment (please complete the following information)**

 - Windows 10 PRO 64bit
 - Browser Chrome Version 107.0.5304.121
 - Wallet Metamask

some suggestions from me that must be addressed immediately by the team
-increase the loading speed of new back end servers that supply websites with cached data for pools and tokens.
- added a websocket server providing up-to-date pairs and tokens.
- fixed issues with swap amounts and fees calculation when swapping KDEX.
- added on-the-fly pair reserves update when swapping/managing positions.
- small improvements to the governance page

**Comment by Homer-Klaytn** [comment]
@dwirizaldy20 Fixed and tested, Klay can be swapped for Dex no problem 

Thanks
