### ISSUE TITLE
Feedback and review

### ISSUE THREAD

**Issue by DonaldW19** [klaytn/klaytn-dex-frontend#53]
1. UI is very smooth and light to use
2. Swap , Add Liquidity , Stake , Unstake ,Withdraw  works well
3. didn't find any bugs during the testnet feature test
4. Very fast transaction
5. Goodluck

address :
0x4881B8C19E9F4dbcFca5e0cEEe74F148Eb5939C6
![Screenshot_2022-11-30-18-24-34-41](https://user-images.githubusercontent.com/88226076/204785665-77db5d5b-3c2e-45ba-8789-e4566d22aa1e.jpg)

**Comment by Homer-Klaytn** [comment]
@DonaldW19 Thank you for your testing and we hope to continue delivering high quality features and improvements!
