### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by XNAME223** [klaytn/klaytn-dex-frontend#56]
**Is your request related to a problem? Please describe.**
nothink transaction notification 

**Describe the solution you'd like**
Add transaction notification
**Describe alternatives you've considered**
Notify when swap/add liquid is successful

**Additional context**
Add transaction notification

**Comment by Homer-Klaytn** [comment]
@XNAME223 Thank you for your testing and we hope to continue delivering high quality features and improvements!
