### ISSUE TITLE
My balance not available

### ISSUE THREAD

**Issue by syahid897** [klaytn/klaytn-dex-frontend#58]
![Screenshot_2022-11-30-18-41-00-450_com kiwibrowser browser](https://user-images.githubusercontent.com/81316354/204787719-b99cfd83-730d-4516-9b21-b2ca40531ec0.jpg)
![Screenshot_2022-11-30-18-42-06-531_com kiwibrowser browser](https://user-images.githubusercontent.com/81316354/204787728-d321a437-5972-465b-9db1-6dd44be555fc.jpg)

Why my balance not available, now I can't removed my liquidity. Please fixed this issue

My adress: 0x94c2b05acee96B52CC3c39489Aadd4781D56f637

**Comment by Victorius** [comment]
Hello, @syahid897 
Thanks for your support in testing 1st open-source DEX on Klaytn.

Regarding you user experience in bug appearance we have several question.
Could you describe steps which you made to achieve this bug?
Try to repeat it, please.

**Comment by Homer-Klaytn** [comment]
this doesnt seem to be an issue anymore. Can't replicate it and my balance is always showing
