### ISSUE TITLE
Remove LP Web Bug and Problem with Gas Fee

### ISSUE THREAD

**Issue by leoserein** [klaytn/klaytn-dex-frontend#59]
Hi, I have trying the platform and used windows10 and metamask to doin a test then I've found two major issue about removing LP.
1. First, removing LP page wasn't responsive and all the balances details was not appear correctly. like my attached picture below.
![Screenshot (261)](https://user-images.githubusercontent.com/103092212/204786267-638d5448-119a-42d7-83f2-720c88e248ab.png)
2. Sometimes, remove LP details was showing correctly but when I'm try to remove, the errors pop up was appeared. Like this picture.
![Screenshot (262)](https://user-images.githubusercontent.com/103092212/204788077-e7b9691a-1182-4775-80ef-b5e15985ab64.png)
After some test, I found that the problem was on the gas fees. I need to modify the gas fee manually if I want a successful transactions on removing LP page.

That's all my faced issue, hope the platform will be more responsive and it can help the team to improve your platform. Thank you!

My Address: 0xD7FCE914df1876192A2b73C7c17f1dd00C2dc266

**Comment by Homer-Klaytn** [comment]
After testing this, i was able to remove the liquidity without any errors, didnt need to manually update the gas fees after i selected removal. I was also able to remove with the percentage % bar and the with a direct amount as well.
