### ISSUE TITLE
Feature request & suggestion

### ISSUE THREAD

**Issue by PanjiHikaru27** [klaytn/klaytn-dex-frontend#60]
![IMG_20221130_182559](https://user-images.githubusercontent.com/53354481/204788264-b001f7f6-1114-40bd-92e2-6edb58f780d8.jpg)
![IMG_20221130_184113](https://user-images.githubusercontent.com/53354481/204788286-8c1cc13f-17e2-4b92-bb6f-6f78838a66bf.jpg)
The next picture is about suggestion/ idea from Me:
- Picture Number 1: Add balance percentage feature (25%, 50%, 75% for convenient user balance management) Not only MAX because this feature is so important for the user
- Picture Number 2: I suggest you to add dark mode also add social media widgets/ social media buttons feature for accessing, join or follow Your Social Media. And Please add more feature like support feature, it will be helping users if They found any problem. Language feature would be great for users to choose/ using another language

My Address: 0x6B1c9112Df0bE9D9A3e8987A[96584519](tel:96584519)f6f[81946](tel:81946)

**Comment by Homer-Klaytn** [comment]
@PanjiHikaru27 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
