### ISSUE TITLE
Add lp failed

### ISSUE THREAD

**Issue by Galihsaptahadi** [klaytn/klaytn-dex-frontend#61]
there was a slight problem when adding liquidity/lp tokens with the kdex/usdt pair, the problem I experienced was a failure.
the problem is that the supply that I did didn't work as it should.

I use a mobile phone with Android OS 11 browser misses. With metamask wallet extension. 

https://user-images.githubusercontent.com/95604585/204788201-048eb680-074f-4448-aa9b-2d0319cb22c5.mp4

You can chek my transaction on address
0xFC85a441009D914eD6798e47Dd224C3d6F90DFEd

**Comment by Homer-Klaytn** [comment]
@Galihsaptahadi 
Right now we dont support mobile browser, can't say if they work as it should. In terms of your transaction issues, it has been fixed and Dex and USDT liquidity combo can be added with no problem
