### ISSUE TITLE
Remove Liqudity Bug

### ISSUE THREAD

**Issue by ArvianArnanda** [klaytn/klaytn-dex-frontend#62]
**Describe the bug**
Cant Remove Liquidity in Dex

**How to reproduce**
Liquidity -> Remove Liqudity -> Set Amount Remove -> Remove

**Expected behavior**
Run All Feature Sucess

**Attachments**
![image](https://user-images.githubusercontent.com/70937983/204790230-8e1535a3-5f72-41ad-a395-55955f50bde6.png)

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS Windows 10
 - Wallet Metamask

**Additional context**
-

**Comment by Victorius** [comment]
Hello, @ArvianArnanda 
Thanks for your support in testing 1st open-source DEX on Klaytn.

Regarding you user experience in bug appearance we have several question.
Could you describe steps which you made to achieve this bug?
Try to repeat it, please. It is important to fully describe all steps (including time perspectives)

**Comment by Homer-Klaytn** [comment]
Able to remove liquidity in Dex with all different types of combinations
