### ISSUE TITLE
Dex UI

### ISSUE THREAD

**Issue by aristahanif** [klaytn/klaytn-dex-frontend#64]
0xa89EA4C7828bB5A8b8845865E62561A267E279aF

i love the dex ui, simple--without unnecessary animation and material, and most importantly have clear navigation buttons. all features is working, speed loading very smooth, i tried on many device resolution and it's working perfectly. Great job dev!!!
maybe you can add dark mode because many users prefer using dark mode.

**Comment by Homer-Klaytn** [comment]
@aristahanif Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
