### ISSUE TITLE
Default Slippage value

### ISSUE THREAD

**Issue by godevid** [klaytn/klaytn-dex-frontend#65]
While first time connecting wallet into the platform, and try to swap always returned on failed transactions after wallet confirmations. After try check on slippage settings the default value was 0 and make tx is failed. Kindly make the default slippage value is 0.5 or more to prevent failed tx, or kindly make a confirmations pop up for choose slippage settings if not set up/still on 0% before popup confirmations swap.

**How to reproduce**
Connecting new wallet to the platform then do swap after claiming test token. There will be failure tx and its happen because default slippage value given by platform is 0%.

**Expected behavior**
The default slippage should be had same value with the minimal slippage value on slippage selections settings. Not 0%.

**Attachments**
N/A

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS: Windows, browser: Chrome
 - Wallet: Kaikas

**Comment by Homer-Klaytn** [comment]
@godevid Default slippage has been updated to 0.5%.

Thank you
