### ISSUE TITLE
HTML Injection leads to Open Redirect on https://dex.baobab.klaytn.net/voting through third party

### ISSUE THREAD

**Issue by magrisya** [klaytn/klaytn-dex-frontend#66]
**Describe the bug**
Hi,
I would like to report HTML Injection and possible cross site scripting (XSS) vulnerability in https://dex.baobab.klaytn.net/voting/.
Due to a lack of  sanitization and validation in parameter affected, 
we can input HTML Tag and system will render it.

**How to reproduce**
 1. go to https://snapshot.org/#/toniya.eth
 2. create new proposals https://snapshot.org/#/toniya.eth/create/0
 3. input ur html injection payloads like a : 
 ```
<h1><font color="red">Malicious Vote!!</font></h1>

<a href=http://evil.com>Vote Here!!</a>
```
 4. and then check ur vote on https://dex.baobab.klaytn.net/voting/

my vote : https://dex.baobab.klaytn.net/voting/0xcac6c3e48ff1668c7c995de5c9fcbd46ec750f29714b1d1564c901ac5271146a 

**Expected behavior**
because it's a problem of lack of sanitization and validation and you should issue a fix on this issue.

**Attachments**
![Screenshot_3](https://user-images.githubusercontent.com/43703018/204794152-cbc94a95-482d-435c-baf7-ba2016f92bfc.png)

**Comment by Homer-Klaytn** [comment]
@magrisya Tried this scenario and the HTML injections can't be added now.

Thank you
