### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ojannajo** [klaytn/klaytn-dex-frontend#69]
There is no problem whatsoever when making transactions, comfortable simple and elegant. Continue to develop to achieve maximum results and be able to compete in the future.

0x915D72Fd6Cf53c34D6b7C238be60a79d5214C452

**Comment by Homer-Klaytn** [comment]
@Ojannajo Thank you for your testing and we hope to continue delivering high quality features and improvements!

**Comment by Ojannajo** [comment]
Thank you

Pada tanggal Kam, 19 Jan 2023 pukul 14.46 Homer-Klaytn <
***@***.***> menulis:
