### ISSUE TITLE
interesting features

### ISSUE THREAD

**Issue by jalmowidodo** [klaytn/klaytn-dex-frontend#70]
**Is your request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jalmowidodo** [comment]
#68 really hope it will be a good project.  Where is the project with the innovated developer for this project.  Let's build a good and strong community so that this token will be even better.
My address : 0x7f9A4f74D33629C2835Fb407416c870cD2D8F77b

**Comment by Homer-Klaytn** [comment]
@jalmowidodo Thank you for your testing and we hope to continue delivering high quality features and improvements!
