### ISSUE TITLE
LP issue/bug

### ISSUE THREAD

**Issue by emeraldsummer15** [klaytn/klaytn-dex-frontend#71]
I encountered 2 LP bugs:
1. I can not remove LP
    Neither the page or the button give any response
2. Sometimes the LP page doesn't show some of my LP positions ( I have 3 LP positions but the page only shows 1 LP position)
    I've already refreshed /reload the page but it still doesn't work

Please solve these problems/bugs

My address: 0x604E2cFd469E1030F029e13B7E0CD88A15193314
![klay ava1](https://user-images.githubusercontent.com/85456159/204798455-fc53b211-084b-4266-974c-ecb3fbb22945.jpg)
![klay ava 2](https://user-images.githubusercontent.com/85456159/204798532-136d2b9a-b218-42e1-9ba9-1617222eca43.jpg)
![klay ava 3](https://user-images.githubusercontent.com/85456159/204798572-25615531-f40c-4d9d-950a-d8ddd6b204b8.jpg)

**Comment by Victorius** [comment]
Hello, @emeraldsummer15 
Thanks for your support in testing 1st open-source DEX on Klaytn.

Regarding you user experience in bug appearance we have several question.
Could you describe steps which you made to achieve this bug?
Try to repeat it, please.

**Comment by Homer-Klaytn** [comment]
Was able to add multiple new liquidity and after clicking on refresh it displayed it everytime
