### ISSUE TITLE
MY FEEDBACK ON THE TESTNET

### ISSUE THREAD

**Issue by Lovelyhash** [klaytn/klaytn-dex-frontend#72]
![Screenshot (5)](https://user-images.githubusercontent.com/112013515/204799299-0ee2a591-01ff-45ca-8c8f-b3ca92726fdb.png)

This is by far the most mind blowing testnet i've ever tested, the guide i followed explain everything and it all works like it should from swaps, add liquidity, staking, checking pools all the steps are great to follow most importantly casting vote too. Big success and growth to the team and this project.

0x8Ff56fc87b66ab9104DB2548c03d20e521A60a4F

**Comment by Homer-Klaytn** [comment]
@Lovelyhash Thank you for your testing and we hope to continue delivering high quality features and improvements!
