### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by efendi-boy** [klaytn/klaytn-dex-frontend#73]
![Screenshot_2022-11-30-17-39-03-646_com kiwibrowser browser](https://user-images.githubusercontent.com/80804533/204801657-457d0111-eb83-4e94-84c8-7532ddfca422.jpg)

There was an error while swapping, please fix it as soon as possible

My contrack addres
0x4D2bA6B91842Be0E766EFe3a354F7B4dDD31c437

**Comment by Homer-Klaytn** [comment]
<img width="596" alt="Screen Shot 2022-12-29 at 10 38 13 AM" src="https://user-images.githubusercontent.com/113971437/209892418-bfd6efac-2479-4554-a5d2-ad13c82e42a5.png">
@efendi-boy  Should have no problem swapping now!

Thanks
