### ISSUE TITLE
Fitur & bug

### ISSUE THREAD

**Issue by efendi-boy** [klaytn/klaytn-dex-frontend#74]
![Screenshot_2022-11-30-17-39-03-646_com kiwibrowser browser](https://user-images.githubusercontent.com/80804533/204802480-f586e7e2-36ed-4ed2-81ea-965d98d732ac.jpg)

* There was an error while swapping, please fix it as soon as possible

* create really interesting dapps to get people interested in this project

0x4D2bA6B91842Be0E766EFe3a354F7B4dDD31c437

**Comment by Homer-Klaytn** [comment]
@efendi-boy The Swapping error is fixed now, thank you for testing!
