### ISSUE TITLE
Soramitsu x Klatyn Feedback and Improvement 

### ISSUE THREAD

**Issue by lingardiwiratama** [klaytn/klaytn-dex-frontend#76]
I have tried trading on the Soramitsu x Klatyn testnet. There I did swap, add lp, farm, stake, and withdraw. I didn't find any obstacles there, the transaction went very smoothly without any failed transactions. But I can suggest that for website development, the development team must add a light & dark feature so that users can choose what theme they want to use when the environment is dark or light. Overall I really like transacting here, keep up your hard work dev.

0xECdDf5398Dc6B42Ed678EFC24813B9868DA5CcBB

![IMG_20221130_200756_921](https://user-images.githubusercontent.com/85468720/204805864-633c0603-4c36-43f7-af83-84d5b4dbd9e5.jpg)
![IMG_20221130_200759_341](https://user-images.githubusercontent.com/85468720/204805872-a27763b1-2dbd-4619-81ac-9041fe50cc27.jpg)
![IMG_20221130_200801_247](https://user-images.githubusercontent.com/85468720/204805878-503abb65-acf4-492e-a655-96447a51293e.jpg)
![IMG_20221130_200802_844](https://user-images.githubusercontent.com/85468720/204805884-f1e6e85a-5407-4d7b-9f72-6f4b6f2753fc.jpg)

**Comment by Homer-Klaytn** [comment]
@lingardiwiratama Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
