### ISSUE TITLE
removed liquidity

### ISSUE THREAD

**Issue by Hermantoo** [klaytn/klaytn-dex-frontend#77]
I tried to withdraw liquidity, at first I was confused because the token that I was about to withdraw did not come out with a nominal balance.
but I tried again several times and finally I was able to remove the liquid too.
maybe that's all I can say at this time, thank you.
![Screenshot_2022-11-30-19-49-59-64_4d38fce200f96aeac5e860e739312e76.jpg](https://user-images.githubusercontent.com/119505342/204806800-dd95a492-abd6-474c-ad8f-ab1c0c008379.jpg)

**Comment by Homer-Klaytn** [comment]
@Hermantoo Thank you for your testing and we hope to continue delivering high quality features and improvements!
