### ISSUE TITLE
My feedback and sugestion

### ISSUE THREAD

**Issue by Azis94** [klaytn/klaytn-dex-frontend#79]
everything went smoothly approve, trade, liquidity,remove and also farming everything was ok, but unfortunately this application does not have a stake feature on one of the coins in the application for example after withdrawing from farming coin dex it can only be traded. it would be great if coin dex can also be staked so users can get more from your app
0x725426Dd56484f946D0d501D9330Ae7a09Fe6C04
!
![Screenshot_2022-11-30-21-12-59-335_com kiwibrowser browser](https://user-images.githubusercontent.com/74254937/204807161-3e34ab01-4d0b-48a2-b98b-cc375a95e13d.jpg)
[Uploading Screenshot_2022-11-30-21-13-23-395_com.kiwibrowser.browser.jpg…]()

**Comment by Homer-Klaytn** [comment]
@Azis94 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
