### ISSUE TITLE
Vote 

### ISSUE THREAD

**Issue by Hermantoo** [klaytn/klaytn-dex-frontend#80]
I want to ask about vote, what is this vote for and what are the benefits for it, do you think?

![Screenshot_2022-11-30-19-47-23-67_4d38fce200f96aeac5e860e739312e76.jpg](https://user-images.githubusercontent.com/119505342/204809126-52733fb2-c855-46f7-ba70-f81d2755ff9a.jpg)
![Screenshot_2022-11-30-19-46-29-78_4d38fce200f96aeac5e860e739312e76.jpg](https://user-images.githubusercontent.com/119505342/204809173-921883f7-896d-4eda-aced-9d163a73e66b.jpg)

**Comment by Homer-Klaytn** [comment]
@Hermantoo Voting was to gather understanding from our users and for other users to interact with one another. It also allows us to understand what the users may want to see in terms of improving the dex as a system.

Thank you
