### ISSUE TITLE
Error Swap preparation failed

### ISSUE THREAD

**Issue by unt443** [klaytn/klaytn-dex-frontend#81]
**Describe the bug**
error Swap preparation failed

**How to reproduce**
when trying to swap from KLAY to DEX, there is a bug "Swap preparation failed" but when swapping KLAY to USDT the transaction runs normally, as well as when swapping USDT to DEX.

**Expected behavior**
bug fix "Swap preparation failed" when swapping KLAY to Dex

![ds](https://user-images.githubusercontent.com/100983236/204813708-a3d081ca-2da5-452d-bc5b-9d0998cfb6ee.png)
![Untitled](https://user-images.githubusercontent.com/100983236/204814237-12c1c032-39d0-43b5-b471-e38afb734cad.png)

**Comment by Homer-Klaytn** [comment]
@unt443 Should have no problem swapping Klay to Dex now
Thank you
