### ISSUE TITLE
Identification of bug

### ISSUE THREAD

**Issue by MrsAdeojo** [klaytn/klaytn-dex-frontend#82]
When confirming transactions there is a huge delay, you will have to approve transaction multiple times from your wallet before the actual transaction is confirmed 
**Describe the bug**
The bug delays confirmation of transactions.

**How to reproduce**
When confirming transaction like adding liquidity, swapping it takes a long time to confirm, I will have to approve multiple times on my wallet before transaction is actually approved.

**Expected behavior**
I expect an easy and smooth transaction confirmation.

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - klaytn-dex-frontend release version that exhibits the issue
 - OS and its version [e.g. macOS/10.14]
 - Wallet and its version used [e.g. Kaikas, metamask]
 - wallet used metamask.

**Additional context**

**Comment by Victorius** [comment]
Thanks, for you response. 
Try to open Expert Mode.
In swap page, click on settings button. In opened window turn on the toggle button and confirm it.

Thanks!
