### ISSUE TITLE
feedback after testing the testnet

### ISSUE THREAD

**Issue by lancecruxx** [klaytn/klaytn-dex-frontend#83]
![Screenshot (7)](https://user-images.githubusercontent.com/108823126/204815548-ecc842d0-6cb3-4ac6-abb2-7be0460098c9.png)
no bugs
swaps,adding of liquidity,removing liquidity, staking lp, checking pools,
all the features presented in the testnets are perfect, didn't detect any bugs at all.

0xafcb1A9f66041D7ec5823D7746CD135b5E7F1F21

**Comment by Homer-Klaytn** [comment]
@lancecruxx Thank you for your testing and we hope to continue delivering high quality features and improvements!
