### ISSUE TITLE
Soramitsu Testnet Feedbacks

### ISSUE THREAD

**Issue by crucifycruxx** [klaytn/klaytn-dex-frontend#84]
![Screenshot (8)](https://user-images.githubusercontent.com/119511221/204818745-4db90cb1-645d-44ec-842f-1d0f8528b9d0.png)
personally i didn't detect any bugs , all the functions present in the testnet  from swap, liquidity,staking,farming,casting of vote all the features is superb, can't wait to see how big this will become 

0x2163b51c66d684ba5fd5b69be41ffd2fcce7bb99

**Comment by Homer-Klaytn** [comment]
@crucifycruxx Thank you for your testing and we hope to continue delivering high quality features and improvements!
