### ISSUE TITLE
/my feedback

### ISSUE THREAD

**Issue by beholhungkul** [klaytn/klaytn-dex-frontend#85]
a great effort bears a tangible result. testnet is perfect and running as expected, I really hope this project can provide positive things for the community when launch day arrives. I can't wait for it!

My address :
0x8E9d6c83Cb0468cd48666f45cB4570D2138e381d

**Comment by Homer-Klaytn** [comment]
@beholhungkul Thank you for your testing and we hope to continue delivering high quality features and improvements!
