### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Bagusadj** [klaytn/klaytn-dex-frontend#86]
Feedback :
Awesome project i have tried all the features. I hope this project can be even better when mainnet arrives. need to improve like UI/UX or other menu. I believe in the dev and team behind all of this! warm greetings from me. 

Ideas :
1. Added dark mode and light mode
2. added history feature

**Comment by Homer-Klaytn** [comment]
@Bagusadj 
Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
