### ISSUE TITLE
error in the swap feature

### ISSUE THREAD

**Issue by rezaaaa22** [klaytn/klaytn-dex-frontend#88]
the swap feature often appears a popup like the image I circled, I don't understand what this is, I can't explain it in detail, the error often appears several times and I have to repeat it to make it work
Device : Android,VIVO Y20
![IMG_20221130_215005](https://user-images.githubusercontent.com/110671416/204831901-a00af480-4601-4fa4-b181-e63a1ef7f6d9.jpg)
![IMG_20221130_214947](https://user-images.githubusercontent.com/110671416/204831917-22c950af-3f79-4423-ad53-4e26f7dd6e0e.jpg)

**Comment by Homer-Klaytn** [comment]
@rezaaaa22 You should have no issues with swapping now!

Thanks
