### ISSUE TITLE
feedback and suggestions 

### ISSUE THREAD

**Issue by NengMusk** [klaytn/klaytn-dex-frontend#89]
**everything went smoothly and fast executed transactions were great. no problem for me. 
and again, the simple wen display ui system makes it easy for users to interact with features on the web, also with light and dark modes that are easy on the eyes.**

**My wallet address : 0x9FFf4f24A6Ab34561690ee2E0D018190c1e71777**

**
![Screenshot_20221130_165326_Kiwi Browser](https://user-images.githubusercontent.com/110114274/204832009-0428c4f3-ca9b-43e7-8f35-a5dfb709fdc2.jpg)
**

**Comment by Homer-Klaytn** [comment]
@NengMusk Thank you for your testing and we hope to continue delivering high quality features and improvements!
