### ISSUE TITLE
here I explain more about the shortcomings of this project in my opinion

### ISSUE THREAD

**Issue by rezaaaa22** [klaytn/klaytn-dex-frontend#90]
deficiency :
-look is too plain , i think you can add image on the background , i think add logo from this project will be more cool
- irregular display on the phone, I think you guys need to fix this because I think a good project is a project that can be used on various devices
-no dark mode,I think this feature is very important for some users including me, I really need this feature at night

suggestions and input:
I think this project is easy to use I am very happy when I make transactions here, from the appearance it is quite neat but you need to add a little color gradient and an image on the background, for all features to work well except for the swap feature, maybe this is just my feedback Thank you

**Comment by Homer-Klaytn** [comment]
@rezaaaa22 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
