### ISSUE TITLE
Theme UI Bugs

### ISSUE THREAD

**Issue by tiramitsuETH** [klaytn/klaytn-dex-frontend#91]
**Describe the bug**
if I do a test on a smartphone and not in desktop mode the UI gets messy and if in desktop mode there is a menu that is less precise
and if I withdraw at stake there is no choice how much I want to withdraw

**How to reproduce**

**Expected behavior**
I hope the web is fixed and compatible with mobile devices, because nowadays many use cellphones for activities, small size, easy to carry anywhere

**Attachments**
![Screenshot_20221130-215930](https://user-images.githubusercontent.com/98076947/204833248-4392216a-1ca7-47b6-954c-faeb7c7c9d0d.png)
![Screenshot_20221130-215943](https://user-images.githubusercontent.com/98076947/204833262-46433987-3a1f-4d5a-abb0-644f33215cf5.png)

**Environment (please complete the following information)**
 - klaytn-dex-frontend 
 - Android Version 12
 - Wallet Metamask

**Additional context**

**Comment by Homer-Klaytn** [comment]
@Xvan122 Mobile usage of the Dex was not part of this development scope, we consider this to be a non-issue since the desktop browser is working accordingly.
