### ISSUE TITLE
Add more feature

### ISSUE THREAD

**Issue by tiramitsuETH** [klaytn/klaytn-dex-frontend#94]
1. added a slider to make transactions such as deposits, withdrawals, staking and others
2. Add dark mode and light mode features
3.Optimize UI/UX For mobile devices
![Screenshot_20221130-221624](https://user-images.githubusercontent.com/98076947/204837372-bb6ed320-dcff-4fc0-ae76-03e10a2041b5.png)

**Comment by Homer-Klaytn** [comment]
@Xvan122 Thank you for your suggestions, we've taken your request and noted it within our potential enhancement document list!
