### ISSUE TITLE
Failed while confirming adding liquidity

### ISSUE THREAD

**Issue by BangArmoy** [klaytn/klaytn-dex-frontend#95]
1. When I want to add liquidity with the maximum number of existing tokens it cannot be done and there is a failure when confirming the blokchain. then I repeated adding liquidity with a small number of tokens without any decimals in the number of tokens and it succeeded in confirming the addition of liquidity. Here are my failed transactions https://baobab.scope.klaytn.com/tx/0xa6c63682b29cd6e0454e2f7f92f7c5d0ca4a7f6d4d6c18856bbdec4075360c03?tabId=internalTx

2. I can't remove liquidity. the button to clear liquidity is not working and my liquidity balance is not detected.
![likuditas](https://user-images.githubusercontent.com/67122026/204840202-06d0e0ad-5cfd-452d-a9c0-05ae6ee365df.png)

this my wallet testnet: 0xd436B2c2814b794bDa0371794431ed67529842B3

![metamsk](https://user-images.githubusercontent.com/67122026/204838977-26eef6d3-9860-4475-8cc0-ddbcd888e421.png)

**Comment by Victorius** [comment]
Hello, @BangArmoy 
Thanks for your support in testing 1st open-source DEX on Klaytn.

Regarding you user experience in bug appearance we have several question.
Could you describe steps which you made to achieve this bug?
Try to repeat it, please.

**Comment by Homer-Klaytn** [comment]
Was able to add maximum amount of liquidity on two separate coins with no issues and was also able to remove the maximum amount as well
