### ISSUE TITLE
Embrassing

### ISSUE THREAD

**Issue by 0xFerozz** [klaytn/klaytn-dex-frontend#97]
So embrassing! 
![image_2022-11-30_231657659](https://user-images.githubusercontent.com/88267510/204851052-174f91b1-21f3-45bf-aa2d-834de7e45be4.png)
![image_2022-11-30_231712623](https://user-images.githubusercontent.com/88267510/204851121-5f17ea1b-d20a-4d5c-be70-9929e14472ff.png)

i just tested your DEX and here what i got :
1. there's no any problem.
2. it was smooth af from i got the faucet until i found the vote display. 
3. there's a lot of menu that user can easily use this facility.
hahaha i'm so happy to run this testnet. so wen this will be huge?

**Comment by Homer-Klaytn** [comment]
@Txtdarisaham Thank you for your testing and we hope to continue delivering high quality features and improvements!
