### ISSUE TITLE
My Feedback 0xbC51C21a260554031424580b431acbb0845DbC52

### ISSUE THREAD

**Issue by abdikonoha** [klaytn/klaytn-dex-frontend#98]
**Is your request related to a problem? Please describe.**
A clear and concise description of what the problem is. all transactions run smoothly, ui/ux is very simple, almost the same as most dex designs in general, but instead it makes it very easy for users to transact on this platform.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. maybe you can start with a new UI UX design, which is fresher to the eye, can add a dark mode and other foreign language options. and don't forget to add transaction history, to make it easier for users to recap their funds
![klaytn tesnet](https://user-images.githubusercontent.com/106908636/204856689-c460397b-42aa-41f1-a161-cfca79f65d8e.PNG)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. maybe an alternative can add a background to the dex and add a dark mode

**Additional context**

**Comment by Homer-Klaytn** [comment]
@abdikonoha Thank you for your testing and we hope to continue delivering high quality features and improvements!
