### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by neni21** [klaytn/klaytn-dex-frontend#99]
I found one bug thats it i get slow transaction
But ovel all working fine

My adress : 0xa477b2d2042057026Af75EeE995e54637d808791

**Comment by Homer-Klaytn** [comment]
@neni21 Thank you for reporting this issue! At the moment, we cant identify the exact reason why you may had a slower transaction. If this repeadtly occurs, please let us know when we will investigate this matter. If you could add some additional screenshots and the exact duration of how long the transaction it took, that would be great as well.
Thank you!
